language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install pybind11
  - pip install -e ".[testing]"

script:
  - pytest --cov cechmate

after_success:
  - bash <(curl -s https://codecov.io/bash)
